#NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [2]:
import numpy as np

#List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0017722080000002194


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0006466729999994314


#Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.06180442 0.35700298 0.90695408 0.03091635]
 [0.58655837 0.66048197 0.29741526 0.89522409]
 [0.75529751 0.8197227  0.89382064 0.85936446]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[24 82 43 91 73]
 [98 11 52 38 38]
 [13 68 44 21 11]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

#Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[66 80 57 82 62]
 [61 81 62 75 65]
 [24 43 42 35 11]
 [64 70 50 80 45]
 [70 23 53 80 23]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


#Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 2 0]
 [8 8 6]
 [5 7 0]]
[[15 10 13]
 [18 14 14]
 [12 13 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 12 13]
 [26 22 20]
 [17 20 10]]
[[ -8  -8 -13]
 [-10  -6  -8]
 [ -7  -6 -10]]
[[105  20   0]
 [144 112  84]
 [ 60  91   0]]
[[0.46666667 0.2        0.        ]
 [0.44444444 0.57142857 0.42857143]
 [0.41666667 0.53846154 0.        ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[4 7 7]
 [3 9 9]
 [4 9 7]]
[[11 12 10]
 [19 14 16]
 [10 19 15]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19 17]
 [22 23 25]
 [14 28 22]]
[[ -7  -5  -3]
 [-16  -5  -7]
 [ -6 -10  -8]]
[[ 44  84  70]
 [ 57 126 144]
 [ 40 171 105]]
[[0.36363636 0.58333333 0.7       ]
 [0.15789474 0.64285714 0.5625    ]
 [0.4        0.47368421 0.46666667]]


#Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 2 2]
 [8 0 7]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 8]
 [2 0]
 [2 7]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 0]
 [2 5 9]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 2]
 [1 5]
 [0 9]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 3 7]
 [4 6 6]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 3]
 [7 4]
 [6 6]]
(3, 2)


#Some other Methods

Array indexing and slicing

In [4]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[2:5])
print(arr[2:])
print(arr[:5])
print(arr[::-1])

3
[3 4 5]
[3 4 5 6 7 8]
[1 2 3 4 5]
[8 7 6 5 4 3 2 1]


Statistical Operations

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.cumsum(arr))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

result=arr*2
print(result)

result=arr[arr>8]
print(result)

1
9
45
[ 1  3  6 10 15 21 28 36 45]
5.0
5.0
2.581988897471611
6.666666666666667
[ 2  4  6  8 10 12 14 16 18]
[9]


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])
result=arr[arr>5]
print(result)

result=arr[arr%2==0]
print(result)

[6 7 8 9]
[2 4 6 8]


In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9])
result=np.where(arr%2==0,0,arr)
print(result)

[1 0 3 0 5 0 7 0 9]


In [16]:
arr=np.array([1,2,3,4,5,6,7,8,9])
result=np.where(arr>5,0,arr)
print(result)


[1 2 3 4 5 0 0 0 0]


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9])
sorted=np.sort(arr)
print(sorted)

[1 2 3 4 5 6 7 8 9]


In [21]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.array([11,12,13,14,15,16,17,18,19,20])
result=np.concatenate((arr1,arr2))
print(result)

split_arr=np.split(result,5) #into 5 parts
print(split_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15, 16]), array([17, 18, 19, 20])]


In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

int_arr=arr.astype(int)
print(int_arr)

float_arr=arr.astype(float)
print(float_arr)

str_arr=arr.astype(str)
print(str_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [28]:
array1 = np.random.randint(0,10,(2,3))
array2 = np.random.randint(0,10,(3,2))
print(array1)
print(array2)
dot_product=np.dot(array1,array2)
print(dot_product)

[[0 2 0]
 [1 6 9]]
[[9 4]
 [8 0]
 [5 9]]
[[ 16   0]
 [102  85]]


In [30]:
array1 = np.random.randint(0,10,(2,2))
determinant=np.linalg.det(array1)
print(determinant)

-6.0
